### PR TITLE
Support to indexing a field named “_childDocuments_”

### PR DESCRIPTION
**Pull request by KimDahye**
- When a field name is equal to `_childDocuments_`, it is specially treated. (Each fields of its element type are added to solr fields, and its elements are added as child documents.)
- config added: “gen_uniq_child_key”

### CODE REVIEW

**Comment by adymimos** [comment]
@KimDahye , I'm also facing the same issue. I'm trying to index Open Street Map data which is in parquet format. But the structure is similar to `_childDocuments_` but field name is `tags`. Currently field name is hard coded, can it be changed to a option value; so that any nested tags can be indexed

    scala> osm.printSchema
    root
    |-- id: long (nullable = true)
    |-- version: integer (nullable = true)
    |-- timestamp: long (nullable = true)
    |-- changeset: long (nullable = true)
    |-- uid: integer (nullable = true)
    |-- user_sid: string (nullable = true)
    |-- tags: array (nullable = true)
    |    |-- element: struct (containsNull = true)
    |    |    |-- key: string (nullable = true)
    |    |    |-- value: string (nullable = true)
    |-- latitude: double (nullable = true)
    |-- longitude: double (nullable = true)

**Comment by kiranchitturi** [comment]
Thanks for contributing! I will review this soon

**Comment by KimDahye** [comment]
@adymimos I added a solr config for the field name of child documents. You can set this like [here](https://github.com/KimDahye/spark-solr/blob/8479de4287394444379ed11b0040d93d7f4a65b8/src/test/scala/com/lucidworks/spark/TestChildDocuments.scala#L21).

**Comment by kiranchitturi** [comment]
@KimDahye Thanks for your contribution! I have added this feature to the master branch. This will be present in the final 3.0.0 release of spark-solr

fyi, I have messed up your branch during a merge commit https://github.com/KimDahye/spark-solr/commits/feature/childdoc. You should pull from spark-solr latest master to your repo

**Comment by rajrohith** [comment]
> @adymimos I added a solr config for the field name of child documents. You can set it like [here](https://github.com/KimDahye/spark-solr/blob/8479de4287394444379ed11b0040d93d7f4a65b8/src/test/scala/com/lucidworks/spark/TestChildDocuments.scala#L21).

@KimDahye 
I tried as you said while pushing nested json with your config  but records are going like every child records are separately not with parent. please let me know how to push  when i search parent record should show all child records belong to that parent.
Thanks
Raj

**Comment by KimDahye** [comment]
@rajrohith Sorry, I haven't follow up spark-solr project for several years, I am not sure I can answer now.

**Pull request merged**
